use super::{checked_slice, read_uleb, MAX_ARCHIVE_ENTRIES, MAX_ARCHIVE_MEMBER, MAX_ARCHIVE_TOTAL};
use std::fmt::Write as _;
use std::io::{Cursor, Read};
use zip::ZipArchive;

fn u16at(d:&[u8],o:usize)->Result<u16,String>{let b=checked_slice(d,o,2)?;Ok(u16::from_le_bytes([b[0],b[1]]))}
fn u32at(d:&[u8],o:usize)->Result<u32,String>{let b=checked_slice(d,o,4)?;Ok(u32::from_le_bytes([b[0],b[1],b[2],b[3]]))}
fn table(size:u32,off:u32,stride:usize,dlen:usize)->Result<(usize,usize),String>{let n=usize::try_from(size).map_err(|_|"DEX table size overflow")?;let o=usize::try_from(off).map_err(|_|"DEX table offset overflow")?;let bytes=n.checked_mul(stride).ok_or("DEX table overflow")?;if o.checked_add(bytes).is_none_or(|e|e>dlen){return Err("DEX table outside input".into())}Ok((n,o))}
fn descriptor(s:&str)->String{let mut p=0;desc_at(s,&mut p)}
fn desc_at(s:&str,p:&mut usize)->String{let b=s.as_bytes();let mut a=0;while b.get(*p)==Some(&b'['){a+=1;*p+=1}let t=match b.get(*p).copied(){Some(b'V')=>"void".into(),Some(b'Z')=>"boolean".into(),Some(b'B')=>"byte".into(),Some(b'C')=>"char".into(),Some(b'S')=>"short".into(),Some(b'I')=>"int".into(),Some(b'J')=>"long".into(),Some(b'F')=>"float".into(),Some(b'D')=>"double".into(),Some(b'L')=>{*p+=1;let st=*p;while b.get(*p).is_some_and(|x|*x!=b';'){*p+=1}s.get(st..*p).unwrap_or("java/lang/Object").replace('/','.')},_=>"Object".into()};*p=(*p+1).min(b.len());format!("{t}{}","[]".repeat(a))}
fn safe_class(s:&str)->String{descriptor(s).replace('.','/').replace(|c:char|!(c.is_ascii_alphanumeric()||c=='/'||c=='_'||c=='$'),"_")}

struct Dex<'a>{d:&'a[u8],strings:Vec<String>,types:Vec<u32>,protos:Vec<(u32,u32,u32)>,methods:Vec<(u16,u16,u32)>,classes:Vec<(u32,u32,u32,u32)>}
impl<'a> Dex<'a>{
 fn parse(d:&'a[u8])->Result<Self,String>{if d.len()<112||!d.starts_with(b"dex\n"){return Err("not DEX".into())}let(ss,so)=table(u32at(d,56)?,u32at(d,60)?,4,d.len())?;let mut strings=Vec::with_capacity(ss);for i in 0..ss{let off=u32at(d,so+i*4)? as usize;let mut p=off;let _=read_uleb(d,&mut p)?;let end=d[p..].iter().position(|b|*b==0).map(|x|p+x).ok_or("unterminated DEX string")?;strings.push(String::from_utf8_lossy(&d[p..end]).into_owned())}
 let(ts,to)=table(u32at(d,64)?,u32at(d,68)?,4,d.len())?;let mut types=Vec::with_capacity(ts);for i in 0..ts{types.push(u32at(d,to+i*4)?)}
 let(ps,po)=table(u32at(d,72)?,u32at(d,76)?,12,d.len())?;let mut protos=Vec::with_capacity(ps);for i in 0..ps{let o=po+i*12;protos.push((u32at(d,o)?,u32at(d,o+4)?,u32at(d,o+8)?))}
 let(ms,mo)=table(u32at(d,88)?,u32at(d,92)?,8,d.len())?;let mut methods=Vec::with_capacity(ms);for i in 0..ms{let o=mo+i*8;methods.push((u16at(d,o)?,u16at(d,o+2)?,u32at(d,o+4)?))}
 let(cs,co)=table(u32at(d,96)?,u32at(d,100)?,32,d.len())?;let mut classes=Vec::with_capacity(cs);for i in 0..cs{let o=co+i*32;classes.push((u32at(d,o)?,u32at(d,o+4)?,u32at(d,o+8)?,u32at(d,o+24)?))}Ok(Self{d,strings,types,protos,methods,classes})}
 fn str(&self,i:u32)->&str{self.strings.get(i as usize).map(String::as_str).unwrap_or("?")}
 fn tdesc(&self,i:u32)->&str{self.types.get(i as usize).map(|x|self.str(*x)).unwrap_or("Ljava/lang/Object;")}
 fn proto(&self,i:u16)->(Vec<String>,String){let Some((_,ret,params))=self.protos.get(i as usize).copied()else{return(vec![],"void".into())};let r=descriptor(self.tdesc(ret));if params==0{return(vec![],r)}let o=params as usize;let n=u32at(self.d,o).unwrap_or(0) as usize;let mut a=Vec::new();for x in 0..n{if let Ok(t)=u16at(self.d,o+4+x*2){a.push(descriptor(self.tdesc(u32::from(t))))}}(a,r)}
 fn method_name(&self,i:u32)->(String,String,Vec<String>,String){let Some((c,p,n))=self.methods.get(i as usize).copied()else{return("Object".into(),"method".into(),vec![],"void".into())};let(a,r)=self.proto(p);(descriptor(self.tdesc(u32::from(c))),self.str(n).to_owned(),a,r)}
 fn code(&self,off:u32)->String{if off==0{return"// abstract/native method".into()}let o=off as usize;let regs=u16at(self.d,o).unwrap_or(0);let ins=u16at(self.d,o+2).unwrap_or(0);let outs=u16at(self.d,o+4).unwrap_or(0);let n=u32at(self.d,o+12).unwrap_or(0) as usize;let mut s=format!("// registers={regs}, ins={ins}, outs={outs}\n");let start=o.saturating_add(16);for pc in 0..n.min(1_000_000){let Ok(w)=u16at(self.d,start+pc*2)else{break};let op=(w&0xff)as u8;let name=match op{0x00=>"nop",0x01=>"move",0x0e=>"return-void",0x0f..=0x11=>"return",0x12..=0x1c=>"const",0x1a=>"const-string",0x22=>"new-instance",0x28..=0x2a=>"goto",0x32..=0x3d=>"if",0x44..=0x51=>"aget/aput",0x52..=0x5f=>"iget/iput",0x60..=0x6d=>"sget/sput",0x6e..=0x72=>"invoke",0x74..=0x78=>"invoke/range",0x90..=0xaf=>"binary-op",_=>"op"};let _=writeln!(s,"// {pc:04x}: {name:<16} 0x{w:04x}")}s}
 fn class_source(&self,ci:u32,access:u32,super_i:u32,data_off:u32)->String{let fq=descriptor(self.tdesc(ci));let simple=fq.rsplit('.').next().unwrap_or(&fq);let package=fq.rsplit_once('.').map(|x|x.0);let mut out=String::new();if let Some(p)=package{let _=writeln!(out,"package {p};\n")}let sup=if super_i==u32::MAX{"java.lang.Object".into()}else{descriptor(self.tdesc(super_i))};let _=writeln!(out,"// PolyDecomp built-in DEX engine\npublic class {simple}{} {{",if sup!="java.lang.Object"{format!(" extends {sup}")}else{String::new()});let _=writeln!(out,"    // access_flags=0x{access:x}");if data_off!=0{let mut p=data_off as usize;let sf=read_uleb(self.d,&mut p).unwrap_or(0);let inf=read_uleb(self.d,&mut p).unwrap_or(0);let dm=read_uleb(self.d,&mut p).unwrap_or(0);let vm=read_uleb(self.d,&mut p).unwrap_or(0);for _ in 0..sf+inf{let _=read_uleb(self.d,&mut p);let _=read_uleb(self.d,&mut p)}let mut idx=0u32;for _ in 0..dm+vm{idx=idx.saturating_add(read_uleb(self.d,&mut p).unwrap_or(0));let af=read_uleb(self.d,&mut p).unwrap_or(0);let co=read_uleb(self.d,&mut p).unwrap_or(0);let(_,name,args,ret)=self.method_name(idx);let params=args.iter().enumerate().map(|(i,t)|format!("{t} p{i}")).collect::<Vec<_>>().join(", ");if name=="<init>"{let _=writeln!(out,"\n    public {simple}({params}) {{")}else{let _=writeln!(out,"\n    public {ret} {name}({params}) {{")};for line in self.code(co).lines(){let _=writeln!(out,"        {line}")}let _=writeln!(out,"        // method_access=0x{af:x}\n    }}")}}
out.push_str("}\n");out}
}

pub fn decompile_dex(data:&[u8])->Result<Vec<(String,String)>,String>{let x=Dex::parse(data)?;let mut out=Vec::new();for(c,a,s,d)in x.classes.iter().copied().take(100_000){let path=safe_class(x.tdesc(c))+".java";out.push((path,x.class_source(c,a,s,d)))}if out.is_empty(){out.push(("DexReport.java".into(),format!("// DEX parsed successfully\n// strings={} types={} methods={} classes=0\n",x.strings.len(),x.types.len(),x.methods.len())))}Ok(out)}
fn safe_zip_name(n:&str)->String{n.replace('\\',"/").split('/').filter(|x|!x.is_empty()&&*x!="."&&*x!="..").collect::<Vec<_>>().join("/")}
pub fn decompile_apk(data:&[u8])->Result<Vec<(String,String)>,String>{let mut z=ZipArchive::new(Cursor::new(data)).map_err(|e|format!("invalid APK: {e}"))?;if z.len()>MAX_ARCHIVE_ENTRIES{return Err("too many APK entries".into())}let mut total=0u64;let mut out=Vec::new();for i in 0..z.len(){let mut e=z.by_index(i).map_err(|e|e.to_string())?;let name=e.name().to_owned();if e.is_dir()||!name.starts_with("classes")||!name.ends_with(".dex"){continue}if e.size()>MAX_ARCHIVE_MEMBER{return Err("DEX member too large".into())}total=total.saturating_add(e.size());if total>MAX_ARCHIVE_TOTAL{return Err("APK expanded size too large".into())}let mut b=Vec::new();e.read_to_end(&mut b).map_err(|e|e.to_string())?;let prefix=safe_zip_name(&name).trim_end_matches(".dex").to_owned();for(p,s)in decompile_dex(&b)?{out.push((format!("{prefix}/{p}"),s))}}if out.is_empty(){Err("APK contains no classes*.dex".into())}else{Ok(out)}}

#[cfg(test)]mod tests{use super::*;#[test]fn descriptors(){assert_eq!(descriptor("[I"),"int[]");assert_eq!(descriptor("Ljava/lang/String;"),"java.lang.String")}#[test]fn uleb(){let mut p=0;assert_eq!(read_uleb(&[0xe5,0x8e,0x26],&mut p).unwrap(),624485)}}
