use super::{checked_slice, printable_strings};
use std::fmt::Write as _;

fn u16at(d:&[u8],o:usize)->Result<u16,String>{let b=checked_slice(d,o,2)?;Ok(u16::from_le_bytes([b[0],b[1]]))}
fn u32at(d:&[u8],o:usize)->Result<u32,String>{let b=checked_slice(d,o,4)?;Ok(u32::from_le_bytes([b[0],b[1],b[2],b[3]]))}
fn u64at(d:&[u8],o:usize)->Result<u64,String>{let b=checked_slice(d,o,8)?;Ok(u64::from_le_bytes([b[0],b[1],b[2],b[3],b[4],b[5],b[6],b[7]]))}

#[derive(Debug)]struct Stream{name:String,offset:usize,size:usize}
fn metadata_root(data:&[u8])->Result<(usize,Vec<Stream>),String>{
 let root=data.windows(4).position(|w|w==b"BSJB").ok_or("CLR metadata signature BSJB not found")?;
 let mut p=root+4;let major=u16at(data,p)?;let minor=u16at(data,p+2)?;p+=8;let vlen=u32at(data,p)? as usize;p+=4;if vlen>1024*1024{return Err("CLR version string too large".into())}let ver=checked_slice(data,p,vlen)?;p+=vlen;p=(p+3)&!3;let _flags=u16at(data,p)?;let count=u16at(data,p+2)? as usize;p+=4;let mut streams=Vec::new();for _ in 0..count.min(128){let off=u32at(data,p)? as usize;let size=u32at(data,p+4)? as usize;p+=8;let rel=data.get(p..).ok_or("truncated CLR stream name")?;let end=rel.iter().position(|b|*b==0).ok_or("unterminated CLR stream name")?;let name=String::from_utf8_lossy(&rel[..end]).into_owned();p+=end+1;p=(p+3)&!3;streams.push(Stream{name,offset:root.checked_add(off).ok_or("CLR stream offset overflow")?,size})}let _=(major,minor,ver);Ok((root,streams))
}
fn identifiers(heap:&[u8],limit:usize)->Vec<String>{let mut out=Vec::new();for part in heap.split(|b|*b==0){if part.len()<1||part.len()>1024{continue}if let Ok(s)=std::str::from_utf8(part){if s.chars().all(|c|c.is_ascii_alphanumeric()||matches!(c,'_'|'.'|'`'|'<'|'>'|'$'))&&s.chars().any(|c|c.is_ascii_alphabetic()){out.push(s.to_owned());if out.len()>=limit{break}}}}out}
fn il_name(op:u16)->&'static str{match op{0x00=>"nop",0x02=>"ldarg.0",0x03=>"ldarg.1",0x04=>"ldarg.2",0x05=>"ldarg.3",0x06=>"ldloc.0",0x07=>"ldloc.1",0x08=>"ldloc.2",0x09=>"ldloc.3",0x0a=>"stloc.0",0x0b=>"stloc.1",0x0c=>"stloc.2",0x0d=>"stloc.3",0x0e=>"ldarg.s",0x11=>"ldloc.s",0x13=>"stloc.s",0x14=>"ldnull",0x15..=0x1e=>"ldc.i4",0x1f=>"ldc.i4.s",0x20=>"ldc.i4",0x21=>"ldc.i8",0x22=>"ldc.r4",0x23=>"ldc.r8",0x25=>"dup",0x26=>"pop",0x27=>"jmp",0x28=>"call",0x29=>"calli",0x2a=>"ret",0x2b=>"br.s",0x2c=>"brfalse.s",0x2d=>"brtrue.s",0x38=>"br",0x39=>"brfalse",0x3a=>"brtrue",0x58=>"add",0x59=>"sub",0x5a=>"mul",0x5b=>"div",0x5d=>"rem",0x5f=>"and",0x60=>"or",0x61=>"xor",0x65=>"neg",0x6f=>"callvirt",0x72=>"ldstr",0x73=>"newobj",0x74=>"castclass",0x75=>"isinst",0x7b=>"ldfld",0x7d=>"stfld",0x7e=>"ldsfld",0x80=>"stsfld",0x8c=>"box",0x8d=>"newarr",0x8e=>"ldlen",0xa5=>"unbox.any",0xd0=>"ldtoken",0xdc=>"endfinally",0xfe01=>"ceq",0xfe02=>"cgt",0xfe04=>"clt",_=>"il"}}
fn il_scan(data:&[u8],start:usize,max:usize)->String{let mut s=String::new();let end=data.len().min(start.saturating_add(max));let mut p=start;let mut count=0;while p<end&&count<4096{let off=p-start;let b=data[p];p+=1;let op=if b==0xfe&&p<end{let x=0xfe00|u16::from(data[p]);p+=1;x}else{u16::from(b)};let name=il_name(op);let _=writeln!(s,"// IL_{off:04x}: {name:<16} opcode=0x{op:04x}");if name=="ret"&&count>4{break}count+=1}s}

pub fn decompile_dotnet(data:&[u8])->Result<String,String>{
 if !data.starts_with(b"MZ"){return Err("not a PE file".into())}let(root,streams)=metadata_root(data)?;let mut out=String::new();out.push_str("// PolyDecomp built-in .NET metadata/IL decompiler\n// No ILSpy or dotnet runtime is used.\n\nusing System;\n\n");let _=writeln!(out,"// metadata root file offset: 0x{root:x}");out.push_str("// streams:\n");for st in &streams{let _=writeln!(out,"//   {:<12} offset=0x{:x} size={}",st.name,st.offset,st.size)}
 if let Some(strings)=streams.iter().find(|s|s.name=="#Strings"){let heap=checked_slice(data,strings.offset,strings.size.min(data.len().saturating_sub(strings.offset)))?;let ids=identifiers(heap,20_000);out.push_str("\nnamespace DecompiledMetadata {\n    public static class RecoveredIdentifiers {\n");for (i,id) in ids.iter().take(10_000).enumerate(){let _=writeln!(out,"        // [{i}] {id}")}out.push_str("    }\n}\n")}
 if let Some(tables)=streams.iter().find(|s|matches!(s.name.as_str(),"#~"|"#-")){let d=checked_slice(data,tables.offset,tables.size.min(data.len().saturating_sub(tables.offset)))?;if d.len()>=24{let valid=u64at(d,8)?;let sorted=u64at(d,16)?;let _=writeln!(out,"\n// metadata tables valid mask: 0x{valid:016x}");let _=writeln!(out,"// metadata tables sorted mask: 0x{sorted:016x}");let mut p=24;for table in 0..64{if valid&(1u64<<table)!=0{if p+4>d.len(){break}let rows=u32at(d,p)?;p+=4;let _=writeln!(out,"// table {table:02}: {rows} rows")}}}}
 out.push_str("\n// Recovered printable strings:\n");for s in printable_strings(data,6,2000){let _=writeln!(out,"// {s:?}")}
 out.push_str("\n// IL candidate stream near metadata. This is structural output; native PE regions are not executed.\n");out.push_str(&il_scan(data,root.saturating_sub(4096),8192));Ok(out)
}

#[cfg(test)]mod tests{use super::*;#[test]fn opcodes(){assert_eq!(il_name(0x2a),"ret");assert_eq!(il_name(0x28),"call")}#[test]fn no_pe(){assert!(decompile_dotnet(b"no").is_err())}}
